import i18n from '@dhis2/d2-i18n'

/** @typedef {'attribute' | 'dataElement' | 'organisationUnit'} EmsFieldMappingKind */

/**
 * EMS field mappings from data/EMS_general/mapping_basic.csv
 * key = Object ID, label = Data Object name
 * @type {Array<{ key: string, label: () => string, kind: EmsFieldMappingKind, category: string, required: boolean, defaultValue: string, helpText: () => string }>}
 */
export const EMS_FIELD_MAPPING_FIELDS = [
    {
        key: 'AMFR',
        label: () => i18n.t('Appliance manufacturer'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'AMFR', nsSeparator: false }),
    },
    {
        key: 'AMOD',
        label: () => i18n.t('Appliance model'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'AMOD', nsSeparator: false }),
    },
    {
        key: 'ASER',
        label: () => i18n.t('Appliance manufacturer serial number'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ASER', nsSeparator: false }),
    },
    {
        key: 'AID',
        label: () => i18n.t('Appliance indentifier'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'AID', nsSeparator: false }),
    },
    {
        key: 'ADOP',
        label: () => i18n.t('Appliance date of production'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ADOP', nsSeparator: false }),
    },
    {
        key: 'APQS',
        label: () => i18n.t('Appliance PQS code'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'APQS', nsSeparator: false }),
    },
    {
        key: 'ACAT',
        label: () => i18n.t('Appliance PQS device type'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ACAT', nsSeparator: false }),
    },
    {
        key: 'LMFR',
        label: () => i18n.t('Logger manufacturer'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LMFR', nsSeparator: false }),
    },
    {
        key: 'LMOD',
        label: () => i18n.t('Logger model'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LMOD', nsSeparator: false }),
    },
    {
        key: 'LSER',
        label: () => i18n.t('Logger serial number'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LSER', nsSeparator: false }),
    },
    {
        key: 'LID',
        label: () => i18n.t('Logger identifier'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LID', nsSeparator: false }),
    },
    {
        key: 'LDOP',
        label: () => i18n.t('Logger date of production'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LDOP', nsSeparator: false }),
    },
    {
        key: 'LSV',
        label: () => i18n.t('Logger software version'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LSV', nsSeparator: false }),
    },
    {
        key: 'LPQS',
        label: () => i18n.t('Logger PQS code'),
        kind: 'attribute',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LPQS', nsSeparator: false }),
    },
    {
        key: 'EID',
        label: () => i18n.t('EMD identifier'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EID', nsSeparator: false }),
    },
    {
        key: 'EMFR',
        label: () => i18n.t('EMD manufacturer'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EMFR', nsSeparator: false }),
    },
    {
        key: 'EMOD',
        label: () => i18n.t('EMD model'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EMOD', nsSeparator: false }),
    },
    {
        key: 'ESER',
        label: () => i18n.t('EMD serial number'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ESER', nsSeparator: false }),
    },
    {
        key: 'EDOP',
        label: () => i18n.t('EMD date of production'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EDOP', nsSeparator: false }),
    },
    {
        key: 'EMSV',
        label: () => i18n.t('EMD software version'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EMSV', nsSeparator: false }),
    },
    {
        key: 'EPQS',
        label: () => i18n.t('EMD PQS code'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EPQS', nsSeparator: false }),
    },
    {
        key: 'CNAM',
        label: () => i18n.t('Compressor Electronic Unit Manufacturer'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CNAM', nsSeparator: false }),
    },
    {
        key: 'CSER',
        label: () => i18n.t('Compressor Electronic Unit Product Code'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CSER', nsSeparator: false }),
    },
    {
        key: 'CSOF',
        label: () => i18n.t('Compressor Electronic Unit Software version'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CSOF', nsSeparator: false }),
    },
    {
        key: 'CDAT',
        label: () => i18n.t('Compressor Electronic Unit production date'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CDAT', nsSeparator: false }),
    },
    {
        key: 'CNAM2',
        label: () => i18n.t('Secondary Compressor Electronic Unit Manufacturer'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CNAM2', nsSeparator: false }),
    },
    {
        key: 'CSER2',
        label: () => i18n.t('Secondary Compressor Electronic Unit Product Code'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CSER2', nsSeparator: false }),
    },
    {
        key: 'CSOF2',
        label: () => i18n.t('Secondary Compressor Electronic Unit Software version'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CSOF2', nsSeparator: false }),
    },
    {
        key: 'CDAT2',
        label: () => i18n.t('Secondary Compressor Electronic Unit production date'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CDAT2', nsSeparator: false }),
    },
    {
        key: 'RELT',
        label: () => i18n.t('Relative Time'),
        kind: 'dataElement',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'RELT', nsSeparator: false }),
    },
    {
        key: 'RTCW',
        label: () => i18n.t('RTC Wakeup'),
        kind: 'dataElement',
        category: 'Administrative',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'RTCW', nsSeparator: false }),
    },
    {
        key: 'ABST',
        label: () => i18n.t('Absolute time in UTC'),
        kind: 'dataElement',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ABST', nsSeparator: false }),
    },
    {
        key: 'RNAM',
        label: () => i18n.t('Region name'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'RNAM', nsSeparator: false }),
    },
    {
        key: 'DNAM',
        label: () => i18n.t('District name'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DNAM', nsSeparator: false }),
    },
    {
        key: 'FNAM',
        label: () => i18n.t('Facility name'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'FNAM', nsSeparator: false }),
    },
    {
        key: 'CID',
        label: () => i18n.t('Country ID'),
        kind: 'attribute',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CID', nsSeparator: false }),
    },
    {
        key: 'FID',
        label: () => i18n.t('Facility ID'),
        kind: 'organisationUnit',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'FID', nsSeparator: false }),
    },
    {
        key: 'LAT',
        label: () => i18n.t('Location / GIS Coordinates / Latitude'),
        kind: 'organisationUnit',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LAT', nsSeparator: false }),
    },
    {
        key: 'LNG',
        label: () => i18n.t('Location / GIS Coordinates / Longitude'),
        kind: 'organisationUnit',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LNG', nsSeparator: false }),
    },
    {
        key: 'LACC',
        label: () => i18n.t('Location accuracy'),
        kind: 'dataElement',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LACC', nsSeparator: false }),
    },
    {
        key: 'SIGN',
        label: () => i18n.t('File integrity check'),
        kind: 'dataElement',
        category: 'Administrative',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'SIGN', nsSeparator: false }),
    },
    {
        key: 'ACSV',
        label: () => i18n.t('AC supply voltage to the appliance'),
        kind: 'dataElement',
        category: 'Environmental',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ACSV', nsSeparator: false }),
    },
    {
        key: 'SVA',
        label: () => i18n.t('AC supply voltage availability'),
        kind: 'dataElement',
        category: 'Environmental',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'SVA', nsSeparator: false }),
    },
    {
        key: 'DCSV',
        label: () => i18n.t('DC supply voltage to the appliance'),
        kind: 'dataElement',
        category: 'Environmental',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DCSV', nsSeparator: false }),
    },
    {
        key: 'HAMB',
        label: () => i18n.t('Ambient relative humidity'),
        kind: 'dataElement',
        category: 'Environmental',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'HAMB', nsSeparator: false }),
    },
    {
        key: 'TAMB',
        label: () => i18n.t('Ambient temperature'),
        kind: 'dataElement',
        category: 'Environmental',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TAMB', nsSeparator: false }),
    },
    {
        key: 'ACCD',
        label: () => i18n.t('AC current drawn by the appliance'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ACCD', nsSeparator: false }),
    },
    {
        key: 'DCCD',
        label: () => i18n.t('DC current drawn by the appliance'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DCCD', nsSeparator: false }),
    },
    {
        key: 'HCOM',
        label: () => i18n.t('Compartment relative humidity'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'HCOM', nsSeparator: false }),
    },
    {
        key: 'TCON',
        label: () => i18n.t('Condenser temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TCON', nsSeparator: false }),
    },
    {
        key: 'TCON2',
        label: () => i18n.t('Secondary Condenser temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TCON2', nsSeparator: false }),
    },
    {
        key: 'CMPS',
        label: () => i18n.t('Compressor speed'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CMPS', nsSeparator: false }),
    },
    {
        key: 'CMPR',
        label: () => i18n.t('Compressor runtime'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CMPR', nsSeparator: false }),
    },
    {
        key: 'TPCB',
        label: () => i18n.t('Compressor Electronic Unit temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TPCB', nsSeparator: false }),
    },
    {
        key: 'CMPS2',
        label: () => i18n.t('Secondary Compressor speed'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CMPS2', nsSeparator: false }),
    },
    {
        key: 'CMPR2',
        label: () => i18n.t('Secondary Compressor runtime'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'CMPR2', nsSeparator: false }),
    },
    {
        key: 'TPCB2',
        label: () => i18n.t('Secondary Compressor Electronic Unit temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TPCB2', nsSeparator: false }),
    },
    {
        key: 'FANS',
        label: () => i18n.t('Fan speed'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'FANS', nsSeparator: false }),
    },
    {
        key: 'BLOG',
        label: () => i18n.t('Logger battery remaining'),
        kind: 'dataElement',
        category: 'Performance',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'BLOG', nsSeparator: false }),
    },
    {
        key: 'TVC',
        label: () => i18n.t('Vaccine Compartment Temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TVC', nsSeparator: false }),
    },
    {
        key: 'TFRZ',
        label: () => i18n.t('Freezer Compartment Temperature'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'TFRZ', nsSeparator: false }),
    },
    {
        key: 'BEMD',
        label: () => i18n.t('EMD battery remaining'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'BEMD', nsSeparator: false }),
    },
    {
        key: 'HOLD',
        label: () => i18n.t('Holdover, autonomy, or independence time'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'HOLD', nsSeparator: false }),
    },
    {
        key: 'LERR',
        label: () => i18n.t('Logger Error codes'),
        kind: 'dataElement',
        category: 'Performance',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'LERR', nsSeparator: false }),
    },
    {
        key: 'EERR',
        label: () => i18n.t('EMD Error codes'),
        kind: 'dataElement',
        category: 'Performance',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'EERR', nsSeparator: false }),
    },
    {
        key: 'ALRM',
        label: () => i18n.t('Alarm condition'),
        kind: 'dataElement',
        category: 'Alarms',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'ALRM', nsSeparator: false }),
    },
    {
        key: 'DORV',
        label: () => i18n.t('Door/lid opening (vaccine compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: true,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DORV', nsSeparator: false }),
    },
    {
        key: 'IDRV',
        label: () => i18n.t('Instantaneous door/lid opening (vaccine compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'IDRV', nsSeparator: false }),
    },
    {
        key: 'DRCV',
        label: () => i18n.t('Number of door/lid openings (vaccine compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DRCV', nsSeparator: false }),
    },
    {
        key: 'DORF',
        label: () => i18n.t('Door/lid opening (freezer/other compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DORF', nsSeparator: false }),
    },
    {
        key: 'IDRF',
        label: () => i18n.t('Instantaneous door/lid opening (freezer compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'IDRF', nsSeparator: false }),
    },
    {
        key: 'DRCF',
        label: () => i18n.t('Number of door/lid openings (freezer/other compartment)'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'DRCF', nsSeparator: false }),
    },
    {
        key: 'MSW',
        label: () => i18n.t('Main ON/OFF switch'),
        kind: 'dataElement',
        category: 'Use',
        required: false,
        defaultValue: '',
        helpText: () => i18n.t('EMS field: {{objectId}}', { objectId: 'MSW', nsSeparator: false }),
    }
]

export const EMS_FIELD_MAPPING_KEYS = EMS_FIELD_MAPPING_FIELDS.map((f) => f.key)

export const EMS_REQUIRED_FIELD_MAPPING_KEYS = EMS_FIELD_MAPPING_FIELDS
    .filter((f) => f.required && f.kind !== 'organisationUnit')
    .map((f) => f.key)

export const EMS_DEFAULT_FIELD_MAPPINGS = Object.fromEntries(
    EMS_FIELD_MAPPING_FIELDS.map((f) => [f.key, f.defaultValue])
)

export const EMS_FIELD_CATEGORIES = [...new Set(EMS_FIELD_MAPPING_FIELDS.map((f) => f.category))]
